### ISSUE TITLE
Design & Build the Drums

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/nauticalanalogue#12]
- [ ] Source mountings for the Drums ; lampshade idea
- [x] Check the size of the drum pads and nature of fixings from @jrmedd
- [ ] Purchase lots of sticks

**Comment by jrmedd** [comment]
![kit](https://cloud.githubusercontent.com/assets/2814421/15302023/9cab8e0a-1ba8-11e6-8cdd-eb7b7be28190.jpg)

**Comment by jrmedd** [comment]
Kit dispatched today. Will measure/report ASAP.

**Comment by jrmedd** [comment]
@cheapjack  Can you get a line on any lampshades once I've gotten your measurements? Or shall I p ass it onto Dave?

**Comment by cheapjack** [comment]
I'll stay looking for ideas/ikeas that could fit the measurements once I've got 'em: ta for the pictures

**Comment by jrmedd** [comment]
So:
- The top of the drum pads (including the rim) are approximately 200mm across. 
- The back of the pads are approximately 225mm across.
- The pads are approximately 45mm deep.
- The clamps are designed to fit around 37mm thick pipes.

**Comment by jrmedd** [comment]
See above for dimensions, @cheapjack. I can clarify more when I get them home. Feel free to fire away with questions. I'm bringing 4 pads and a hihat pedal for the band to do clip switching.

**Comment by jrmedd** [comment]
Tested the pads, everything works a treat.
