### ISSUE TITLE
Get all the additional scaffolding for the pyramid

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/nauticalanalogue#17]
- [ ] 12 clamps
- [ ] 6 feet
- [ ] 2 longer ones
- [ ] 3 up legs
- [ ] 1 upright for the drum stands

**Comment by adavelynch** [comment]
I should have the clamps and 6 feet sorted, Ill find out tomorrow and report.

**Comment by cheapjack** [comment]
great tick 'em off when you find 'em

**Comment by adavelynch** [comment]
Only got 6 clamps
