### ISSUE TITLE
Kit List for Thursday

### ISSUE THREAD

**Issue by adavelynch** [cheapjack/nauticalanalogue#18]
## Dave:
- [ ] 8 Parcans
- [ ] DMX cable
- [ ] DMX USB connector Box
- [ ] Power Cable
- [ ] 6 Scaff Legs
- [ ] Scaff Connectors

Check checklist in issue #17 
- [ ] 12 clamps
- [ ] 6 feet
- [ ] 2 longer ones
- [ ] 3 up legs
- [ ] 1 upright for the drum stands
## Ross
- [x] Prototype guitar pickup and solenoid holder
- [ ] Sub Woofer and cables 
- [ ] Monitor powered speaker
- [ ] Glue guns
- [ ] Glue sticks
- [ ] Gaffa
- [ ] Adrian's Tap set
- [ ] Audio amp ; lost mini one?
## Simon

Metal drill bits and drill

**Comment by jrmedd** [comment]
@adavelynch: got any idea what the DMX/USB connector box is? Can see what it's going to be like for working with Max.

**Comment by adavelynch** [comment]
https://www.enttec.com/docs/dmxusbpro_manual.pdf

**Comment by jrmedd** [comment]
@adavelynch great! Plenty of resources on interfacing with this from Max. Will have a play tomorrow and see what we can do and what looks good.
