### ISSUE TITLE
Order the PA with Linton

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/nauticalanalogue#20]
So the equipment we need is:
- [x] - 5k sub pa system (I've already got 4 subs, if needed, and a mixing desk; he should have a better idea of exactly what size we need based on the audience being about 400 outside)
  2- 4 Mids/Tops
- [ ] - 8 mics (something like SM58 should do it)
- [ ] - 8 mic stands with booms
- [ ] - 4 DI Boxes
- [x] - Monitors (Got 2 x powered Mackies already
- [ ] - Associated cables, etc
- [ ] - Behringer x32 desk
- [ ] - Roger sourced by aPAtT to operate

**Comment by cheapjack** [comment]
@jrmedd any extra cabling we could ask Linton for as part of the hire (DI boxes other odds & ends) add it here plz :)

**Comment by jrmedd** [comment]
Cables I'm picking up are primarily operational for the instrument, so will make sure we've got them for future iterations. Seems like everything else is covered?
