### ISSUE TITLE
Interim horn amp!

### ISSUE THREAD

**Issue by jrmedd** [cheapjack/nauticalanalogue#21]
So, can we source an interim amplifier for the horn tomorrow, @cheapjack or @adavelynch ? Seems Pimoroni aren't as fast as they used to be at shipping out kit. Used to get stuff next day from them, now it's looking like tomorrow at the earliest (and to the office, not my house!)

If I can take the horn away with me tomorrow, I'll test it out back in workshop on Friday.

**Comment by cheapjack** [comment]
will look for something small. Got shit big domestic one as backup

**Comment by jrmedd** [comment]
Don't worry about going too small as it's only an interim job. The little one that will _eventually_ arrive should solve our problems.
