### ISSUE TITLE
Design and Build the pyramid-guitar

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/nauticalanalogue#3]

**Comment by cheapjack** [comment]
- [x]  Design and cut the acrylic for the pyramid-guitar 
- [x] Get advice on tuning and securing the strings from the shed crew in Gostins
- [ ] Mount the pyramid-guitar onto a cross-pole for the piano wire to sit on
- [x] Design and cut the acrylic for the pyramid-guitar 
- [x] Order the piano wire for the pyramid-guitar

**Comment by cheapjack** [comment]
@Simon-Jones7 suggested Brushless motors spinning instead?

**Comment by jrmedd** [comment]
@cheapjack @Simon-Jones7: principle issue there is a) Timing b) Volume c) Fabricating something sturdy that does the job.

**Comment by cheapjack** [comment]
Sticking to the solenoids due to above & as ive partly made this

![pyramid-guitar-bracket-test](https://cloud.githubusercontent.com/assets/128456/15359989/b3abdacc-1d03-11e6-9618-6918cca14655.png)
