### ISSUE TITLE
Design & Build the BathySubWoofer

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/nauticalanalogue#5]
Get measurements off james on drums arrival on Wednesday

**Comment by cheapjack** [comment]
Only build the horn stepper if there's time

**Comment by cheapjack** [comment]
Buy a 12V power supply for the sub amp

**Comment by cheapjack** [comment]
Design and recut the bell frame

**Comment by jrmedd** [comment]
@cheapjack what's the input on the sub? I'll add it to cable requirements. I take it that it's just plug and play power wise?

**Comment by jrmedd** [comment]
How we do we want to get the visual stuff going on this? More LEDs?

**Comment by cheapjack** [comment]
Simon D has a power supply for this will have to check out the inputs on it in the morning and will add to comment in cable requirements

**Comment by cheapjack** [comment]
Visually Simon D seems to be thinking of filling the sphere with beads as a visual thing (if he can get it open) but imagine will need lighting but maybe using one of Dave's led lamps rather than driving more led stupid
