### ISSUE TITLE
Update the guest list

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/nauticalanalogue#8]

**Comment by cheapjack** [comment]
### nautical-analogue
- [x] Dave
  - [x] Jenni Noyes 
- [x] James
  - [x] Janneke Earl
- [x] Ross
  - [x] Claire Chrystall
  - [x] Mark O'Toole
- [x] Simon D
  - [x] Melanie Derwent

### aPAtT
- [ ] Simon J
- [ ] Stephen Cole
- [ ] Chloe Mullett
- [ ] Fabricio Babriolu
  plus possibly
- [ ] Ben Nield
- [ ] Robbie Morris
- [ ] Rob Dean

### aPAtT Guests
- [ ] Gordon Johnstone
- [ ] Sam Smith
- [ ] Alex Ferrada
- [ ] Ash Jones

**Comment by adavelynch** [comment]
Simon J was saying that there will be 7 band members as opposed to 4, We know it's too late for food for them but they should be put on here I think.  Im not sure if they will get guesties or not but worth a try. When you send it in, just say that the band have multiplied or some such.

**Comment by cheapjack** [comment]
Will forward codes on receipt from Kai/Sally
